### ISSUE TITLE
中文版 文档小问题

### ISSUE THREAD

**Issue by TronYY** [LibCity/Bigscity-LibCity#201]
https://bigscity-libcity-docs.readthedocs.io/zh_CN/latest/get_started/quick_start.html
这里支持的模型没显示，按照英文版本  就是复现的模型吧

**Comment by aptx1231** [comment]
感谢反馈，已经修复啦

**Comment by TronYY** [comment]
https://bigscity-libcity-docs.readthedocs.io/zh_CN/latest/tutorial/hyper_tune.html

python hyper_tune.py --task traffc_state_pred --model GRU --dataset METR_LA --space_file sample_space_file
traffic拼写有误

上一个sample_space_file.json缺逗号  
复制进去运行后出现错误
TypeError: The space file does not meet the format requirements,                            when parsing choice type.

```
(Pytorch171) jy@jy-Precision-3630-Tower:~/Bigscity-LibCity$ python hyper_tune.py --task traffic_state_pred --model GRU --dataset METR_LA --space_file sample_space_file
Error processing line 3 of /home/jy/anaconda3/envs/Pytorch171/lib/python3.7/site-packages/googleapis_common_protos-1.53.0-py3.9-nspkg.pth:

  Traceback (most recent call last):
    File "/home/jy/anaconda3/envs/Pytorch171/lib/python3.7/site.py", line 168, in addpackage
      exec(line)
    File "<string>", line 1, in <module>
    File "<frozen importlib._bootstrap>", line 580, in module_from_spec
  AttributeError: 'NoneType' object has no attribute 'loader'

Remainder of file ignored
2021-11-09 17:02:32,052 - INFO - Log directory: ./libcity/log
Traceback (most recent call last):
  File "/home/jy/Bigscity-LibCity/libcity/pipeline/pipeline.py", line 90, in parse_search_space
    search_space[name] = tune.choice(paras_dict[name]['list'])
NameError: name 'tune' is not defined

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "hyper_tune.py", line 65, in <module>
    other_args=other_args)
  File "/home/jy/Bigscity-LibCity/libcity/pipeline/pipeline.py", line 136, in hyper_parameter
    search_sapce = parse_search_space(space_file)
  File "/home/jy/Bigscity-LibCity/libcity/pipeline/pipeline.py", line 93, in parse_search_space
    when parsing choice type.')
TypeError: The space file does not meet the format requirements,                            when parsing choice type.
```

**Comment by WenMellors** [comment]
感谢反馈
