### ISSUE TITLE
自动调参工具的问题

### ISSUE THREAD

**Issue by TronYY** [LibCity/Bigscity-LibCity#203]
python hyper_tune.py --task traffic_state_pred --model GRU --dataset METR_LA --space_file sample_space_file
使用后提示

AttributeError: module 'idna' has no attribute 'IDNAError'
和
(raylet) ModuleNotFoundError: No module named 'aiohttp.signals'

```
Traceback (most recent call last):
  File "hyper_tune.py", line 65, in <module>
    other_args=other_args)
  File "/home/jy/Bigscity-LibCity/libcity/pipeline/pipeline.py", line 196, in hyper_parameter
    local_dir='./libcity/cache/hyper_tune', num_samples=num_samples)
  File "/home/jy/.local/lib/python3.7/site-packages/ray/tune/tune.py", line 364, in run
    callbacks, sync_config, metric=metric, loggers=loggers)
  File "/home/jy/.local/lib/python3.7/site-packages/ray/tune/utils/callback.py", line 120, in create_default_callbacks
    _sync_to_driver = detect_sync_to_driver(sync_config.sync_to_driver)
  File "/home/jy/.local/lib/python3.7/site-packages/ray/tune/syncer.py", line 461, in detect_sync_to_driver
    from ray.tune.integration.docker import DockerSyncer
  File "/home/jy/.local/lib/python3.7/site-packages/ray/tune/integration/docker.py", line 5, in <module>
    from ray.autoscaler.sdk import rsync, configure_logging
  File "/home/jy/.local/lib/python3.7/site-packages/ray/autoscaler/sdk.py", line 9, in <module>
    from ray.autoscaler._private import commands
  File "/home/jy/.local/lib/python3.7/site-packages/ray/autoscaler/_private/commands.py", line 28, in <module>
    from ray.autoscaler._private.util import validate_config, hash_runtime_conf, \
  File "/home/jy/.local/lib/python3.7/site-packages/ray/autoscaler/_private/util.py", line 6, in <module>
    import jsonschema
  File "/home/jy/anaconda3/envs/Pytorch171/lib/python3.7/site-packages/jsonschema/__init__.py", line 14, in <module>
    from jsonschema._format import (
  File "/home/jy/anaconda3/envs/Pytorch171/lib/python3.7/site-packages/jsonschema/_format.py", line 240, in <module>
    @_checks_drafts(draft7="idn-hostname", raises=idna.IDNAError)
AttributeError: module 'idna' has no attribute 'IDNAError'
(raylet) Traceback (most recent call last):
(raylet)   File "/home/jy/.local/lib/python3.7/site-packages/ray/new_dashboard/agent.py", line 22, in <module>
(raylet)     import ray.new_dashboard.utils as dashboard_utils
(raylet)   File "/home/jy/.local/lib/python3.7/site-packages/ray/new_dashboard/utils.py", line 20, in <module>
(raylet)     import aiohttp.signals
(raylet) ModuleNotFoundError: No module named 'aiohttp.signals'


```

**Comment by TronYY** [comment]
anaconda虚拟环境下的pip

**Comment by WenMellors** [comment]
目前我们环境内是能够跑的，根据 pipdeptree 分析结果，ray 包依赖于：
```
aiohttp  3.7.4.post0
aiohttp-cors 0.7.0
aioredis 1.3.1
click 7.1.2
colorama 0.4.4
colorful 0.5.4
filelock 3.0.12
gpustat 0.6.0
grpcio 1.36.1
jsonschema 3.2.0
msgpack 1.0.2
numpy 1.21.2
opencensus 0.7.12
prometheus-client 0.10.1
protobuf 3.15.6
py-spy 0.3.5
pyyaml 5.4.1
redis 3.5.3
requests 2.25.1
````
依赖还是很多的，或许可以尝试重新安装一下 ray 包。
您可以尝试以下安装命令：
```
pip install -U ray[tune]==1.2.0 
```

**Comment by TronYY** [comment]
按道理这些在最开始 requirements.txt的时候都装了

**Comment by TronYY** [comment]
把环境重装后仍然提示   感觉ray的优先级难道很特殊？
```
(Big) jy@jy-Precision-3630-Tower:~/Big/Bigscity-LibCity$ sudo python hyper_tune.py --task traffic_state_pred --model GRU --dataset METR_LA --space_file sample_space_f
Traceback (most recent call last):
  File "hyper_tune.py", line 9, in <module>
    from libcity.pipeline import hyper_parameter
  File "/home/jy/Big/Bigscity-LibCity/libcity/pipeline/__init__.py", line 1, in <module>
    from libcity.pipeline.pipeline import run_model, hyper_parameter, objective_function
  File "/home/jy/Big/Bigscity-LibCity/libcity/pipeline/pipeline.py", line 3, in <module>
    import ray
ImportError: No module named ray
 ```

我列出了相关已经安装的包
```
~/Big/Bigscity-LibCity$ pip list
Package                  Version
------------------------ ---------
absl-py                  0.15.0
aiohttp                  3.8.0
aiohttp-cors             0.7.0
aioredis                 1.3.1
aiosignal                1.2.0
async-timeout            4.0.0
asynctest                0.13.0
attrs                    21.2.0
blessings                1.7
cachetools               4.2.4
certifi                  2021.10.8
charset-normalizer       2.0.7
click                    8.0.3
cloudpickle              2.0.0
colorama                 0.4.4
colorful                 0.5.4
decorator                4.4.2
dgl                      0.6.1
fastdtw                  0.3.4
filelock                 3.3.2
flake8                   3.3.0
frozenlist               1.2.0
future                   0.18.2
gensim                   4.0.1
geographiclib            1.52
geopy                    2.0.0
google-api-core          2.2.2
google-auth              1.35.0
google-auth-oauthlib     0.4.6
googleapis-common-protos 1.53.0
gpustat                  0.6.0
grpcio                   1.41.1
hiredis                  2.0.0
hyperopt                 0.2.5
idna                     3.3
importlib-metadata       4.8.2
importlib-resources      5.4.0
joblib                   1.1.0
jsonschema               4.2.1
Markdown                 3.3.4
mccabe                   0.6.1
msgpack                  1.0.2
multidict                5.2.0
networkx                 2.5.1
nltk                     3.2.4
numpy                    1.19.4
nvidia-ml-py3            7.352.0
oauthlib                 3.1.1
opencensus               0.8.0
opencensus-context       0.1.2
pandas                   1.1.5
patsy                    0.5.2
pep8-naming              0.4.1
Pillow                   8.4.0
pip                      21.0.1
prometheus-client        0.12.0
protobuf                 3.19.1
psutil                   5.8.0
py                       1.11.0
py-spy                   0.3.10
pyasn1                   0.4.8
pyasn1-modules           0.2.8
pycodestyle              2.3.1
pyflakes                 1.5.0
pyrsistent               0.18.0
pytest                   3.2.1
python-dateutil          2.8.2
pytz                     2021.3
PyYAML                   6.0
ray                      1.2.0
redis                    3.5.3
requests                 2.26.0
requests-oauthlib        1.3.0
rsa                      4.7.2
scikit-learn             0.24.0
scipy                    1.5.3
sentencepiece            0.1.96
setuptools               58.0.4
six                      1.16.0
smart-open               5.2.1
statsmodels              0.11.0
tabulate                 0.8.9
tensorboard              2.4.1
tensorboard-plugin-wit   1.8.0
tensorboardX             2.2
threadpoolctl            3.0.0
torch                    1.7.1
torchaudio               0.7.2
torchtext                0.6.0
torchvision              0.8.2
tqdm                     4.60.0
typing-extensions        3.10.0.2
urllib3                  1.26.7
Werkzeug                 2.0.2
wheel                    0.37.0
yarl                     1.7.2
zipp                     3.6.0
```

**Comment by TronYY** [comment]
好吧 reboot就好了
