### ISSUE TITLE
json文件解析问题..

### ISSUE THREAD

**Issue by sly111** [LibCity/Bigscity-LibCity#244]
同步到最新版本后，运行程序，例如`python run_model.py --task traffic_state_pred --model GRU --dataset METR_LA`都会提示json文件解析错误（如下），不知道是哪出了问题..之前的版本并不会出现这个问题
Traceback (most recent call last):
  File "run_model.py", line 49, in <module>
    run_model(task=args.task, model_name=args.model, dataset_name=args.dataset,
  File "/root/Bigscity-LibCity/libcity/pipeline/pipeline.py", line 30, in run_model
    config = ConfigParser(task, model_name, dataset_name,
  File "/root/Bigscity-LibCity/libcity/config/config_parser.py", line 25, in __init__
    self._load_default_config()
  File "/root/Bigscity-LibCity/libcity/config/config_parser.py", line 69, in _load_default_config
    task_config = json.load(f)
  File "/root/miniconda/lib/python3.8/json/__init__.py", line 293, in load
    return loads(fp.read(),
  File "/root/miniconda/lib/python3.8/json/__init__.py", line 357, in loads
    return _default_decoder.decode(s)
  File "/root/miniconda/lib/python3.8/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/root/miniconda/lib/python3.8/json/decoder.py", line 353, in raw_decode
    obj, end = self.scan_once(s, idx)
json.decoder.JSONDecodeError: Expecting ',' delimiter: line 408 column 9 (char 15204)

**Comment by aptx1231** [comment]
抱歉，这边已经解决了！
