### ISSUE TITLE
Logging error occurred in traj_loc_pred task

### ISSUE THREAD

**Issue by nehSgnaiL** [LibCity/Bigscity-LibCity#293]
Hi, thanks for the awesome work. 
A logging error happened during the evaluation process. The default task in code https://github.com/LibCity/Bigscity-LibCity/blob/master/run_model.py is working well. However, there was an error that occurred when I switch the task to `traj_loc_pred` using *foursquare_nyc* dataset.

#### Code to Reproduce
```python
    # code changes of main function in run_model.py
    parser.add_argument('--task', type=str, default='traj_loc_pred', help='the name of task')
    parser.add_argument('--model', type=str, default='DeepMove', help='the name of model')
    parser.add_argument('--dataset', type=str, default='foursquare_nyc', help='the name of dataset')
```

#### Actual result
--- Logging error ---

```
Traceback (most recent call last):
  File "D:\Software\Anaconda3\envs\LibCitybased\lib\logging\__init__.py", line 1025, in emit
    msg = self.format(record)
  File "D:\Software\Anaconda3\envs\LibCitybased\lib\logging\__init__.py", line 869, in format
    return fmt.format(record)
  File "D:\Software\Anaconda3\envs\LibCitybased\lib\logging\__init__.py", line 608, in format
    record.message = record.getMessage()
  File "D:\Software\Anaconda3\envs\LibCitybased\lib\logging\__init__.py", line 369, in getMessage
    msg = msg % self.args
TypeError: not all arguments converted during string formatting
Call stack:
  File "xx/Bigscity-LibCity-master/run_model.py", line 43, in <module>
    train=args.train, other_args=other_args)
  File "xx\Bigscity-LibCity-master\libcity\pipeline\pipeline.py", line 63, in run_model
    executor.evaluate(test_data)
  File "xx\Bigscity-LibCity-master\libcity\executor\traj_loc_pred_executor.py", line 108, in evaluate
    self.evaluator.save_result(self.evaluate_res_dir)
  File "xx\Bigscity-LibCity-master\libcity\evaluator\traj_loc_pred_evaluator.py", line 96, in save_result
    self._logger.info('evaluate result is ', json.dumps(self.result, indent=1))
Message: 'evaluate result is '
Arguments: ('{\n "Recall@1": 0.16751398997842068\n}',)
--- Logging error ---
Traceback (most recent call last):
  File "D:\Software\Anaconda3\envs\LibCitybased\lib\logging\__init__.py", line 1025, in emit
    msg = self.format(record)
  File "D:\Software\Anaconda3\envs\LibCitybased\lib\logging\__init__.py", line 869, in format
    return fmt.format(record)
  File "D:\Software\Anaconda3\envs\LibCitybased\lib\logging\__init__.py", line 608, in format
    record.message = record.getMessage()
  File "D:\Software\Anaconda3\envs\LibCitybased\lib\logging\__init__.py", line 369, in getMessage
    msg = msg % self.args
TypeError: not all arguments converted during string formatting
Call stack:
  File "xx/Bigscity-LibCity-master/run_model.py", line 43, in <module>
    train=args.train, other_args=other_args)
  File "xx\Bigscity-LibCity-master\libcity\pipeline\pipeline.py", line 63, in run_model
    executor.evaluate(test_data)
  File "xx\Bigscity-LibCity-master\libcity\executor\traj_loc_pred_executor.py", line 108, in evaluate
    self.evaluator.save_result(self.evaluate_res_dir)
  File "xx\Bigscity-LibCity-master\libcity\evaluator\traj_loc_pred_evaluator.py", line 96, in save_result
    self._logger.info('evaluate result is ', json.dumps(self.result, indent=1))
Message: 'evaluate result is '
Arguments: ('{\n "Recall@1": 0.16751398997842068\n}',)

Process finished with exit code 0
```

**Comment by WenMellors** [comment]
Thanks for your comment. This is a small bug in `traj_loc_pred_evaluator.py`
