### ISSUE TITLE
TypeError: function() argument 1 must be code, not str

### ISSUE THREAD

**Issue by Mardok95** [LibCity/Bigscity-LibCity#324]
Hello, I am sorry to bore you with these little problems but I would need your help as I cannot figure out where the problem is coming from. I managed to install the repo with Pythorch in CPU-only version. I ran a test run through the command I found in the QuickStart guide, then ran the command:

`python run_model.py --task traffic_state_pred --model GRU --dataset METR_LA --gpu false`

Everything worked, I even have the output files showing the successful execution.
I downloaded the "gowalla" dataset and followed the guide, then created a raw_data folder inside which I put the folder named "gowalla," just as I had done for the "METR_LA" dataset. The problem occurs when I try to run this command:
`python run_model.py --task traj_loc_pred --model LSTPM --dataset gowalla --gpu false`

This is the output that I obtain:

```
PS C:\Users\Andrea\Desktop\Bigscity-LibCity> python run_model.py --task traj_loc_pred --model LSTPM --dataset gowalla --gpu false   
2023-01-19 11:15:03,917 - INFO - Log directory: ./libcity/log
2023-01-19 11:15:03,926 - INFO - Begin pipeline, task=traj_loc_pred, model_name=LSTPM, dataset_name=gowalla, exp_id=92087
2023-01-19 11:15:03,926 - INFO - {'task': 'traj_loc_pred', 'model': 'LSTPM', 'dataset': 'gowalla', 'saved_model': True, 'train': True, 'seed': 0, 'gpu': False, 'dataset_class': 'TrajectoryDataset', 'traj_encoder': 'LstpmEncoder', 'executor': 'TrajLocPredExecutor', 'evaluator': 'TrajLocPredEvaluator', 'hidden_size': 500, 'emb_size': 500, 'dropout': 0.8, 'window_size': 24, 'cut_method': 'same_date', 'learning_rate': 0.0001, 'L2': 1e-06, 'batch_size': 32, 'max_epoch': 40, 'clip': 5.0, 'min_session_len': 5, 'max_session_len': 50, 'min_sessions': 2, 'min_checkins': 3, 'num_workers': 0, 'cache_dataset': True, 'train_rate': 0.7, 'eval_rate': 0.1, 'history_type': 'splice', 'gpu_id': 0, 'lr_step': 2, 'lr_decay': 0.1, 'schedule_threshold': 0.001, 'loss_func': 'default', 'load_best_epoch': True, 'hyper_tune': False, 'optimizer': 'adam', 'early_stop_lr': 9e-06, 'debug': False, 'metrics': ['Recall'], 'evaluate_method': 'popularity', 'topk': 1, 'geo': {'including_types': ['Point'], 'Point': {}}, 'usr': {'properties': {}}, 'rel': {'including_types': ['usr'], 'usr': {}}, 'dyna': {'including_types': ['trajectory'], 'trajectory': {'entity_id': 'usr_id', 'location': 'geo_id'}}, 'distance_upper': 100, 'geo_file': 'gowalla', 'dyna_file': 'gowalla', 'usr_file': 'gowalla', 'rel_file': 'gowalla', 'device': device(type='cpu'), 'exp_id': 92087}
Traceback (most recent call last):
  File "run_model.py", line 38, in <module>
    train=args.train, other_args=other_args)
  File "C:\Users\Andrea\Desktop\Bigscity-LibCity\libcity\pipeline\pipeline.py", line 46, in run_model
    dataset = get_dataset(config)
  File "C:\Users\Andrea\Desktop\Bigscity-LibCity\libcity\data\utils.py", line 22, in get_dataset
    config['dataset_class'])(config)
  File "C:\Users\Andrea\Desktop\Bigscity-LibCity\libcity\data\dataset\trajectory_dataset.py", line 32, in __init__
    self.encoder = self.get_encoder()
  File "C:\Users\Andrea\Desktop\Bigscity-LibCity\libcity\data\dataset\trajectory_dataset.py", line 250, in get_encoder
    return getattr(importlib.import_module('libcity.data.dataset.trajectory_encoder'),
  File "C:\Users\Andrea\AppData\Local\Programs\Python\Python37\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "C:\Users\Andrea\Desktop\Bigscity-LibCity\libcity\data\dataset\trajectory_encoder\__init__.py", line 3, in <module>
    from .atstlstm_encoder import AtstlstmEncoder
  File "C:\Users\Andrea\Desktop\Bigscity-LibCity\libcity\data\dataset\trajectory_encoder\atstlstm_encoder.py", line 4, in <module>
    from geopy import distance
  File "C:\Users\Andrea\AppData\Local\Programs\Python\Python37\lib\site-packages\geopy\__init__.py", line 12, in <module>
    from geopy.geocoders import *  # noqa
  File "C:\Users\Andrea\AppData\Local\Programs\Python\Python37\lib\site-packages\geopy\geocoders\__init__.py", line 221, in <module>
    from geopy.geocoders.algolia import AlgoliaPlaces
  File "C:\Users\Andrea\AppData\Local\Programs\Python\Python37\lib\site-packages\geopy\geocoders\algolia.py", line 5, in <module>
    from geopy.geocoders.base import DEFAULT_SENTINEL, Geocoder
  File "C:\Users\Andrea\AppData\Local\Programs\Python\Python37\lib\site-packages\geopy\geocoders\base.py", line 7, in <module>
    from geopy.adapters import (
  File "C:\Users\Andrea\AppData\Local\Programs\Python\Python37\lib\site-packages\geopy\adapters.py", line 53, in <module>
    import aiohttp
  File "C:\Users\Andrea\AppData\Local\Programs\Python\Python37\lib\site-packages\aiohttp\__init__.py", line 6, in <module>
    from .client import (
  File "C:\Users\Andrea\AppData\Local\Programs\Python\Python37\lib\site-packages\aiohttp\client.py", line 35, in <module>
    from . import hdrs, http, payload
  File "C:\Users\Andrea\AppData\Local\Programs\Python\Python37\lib\site-packages\aiohttp\http.py", line 7, in <module>
    from .http_parser import (
  File "C:\Users\Andrea\AppData\Local\Programs\Python\Python37\lib\site-packages\aiohttp\http_parser.py", line 15, in <module>
    from .helpers import NO_EXTENSIONS, BaseTimerContext
  File "C:\Users\Andrea\AppData\Local\Programs\Python\Python37\lib\site-packages\aiohttp\helpers.py", line 667, in <module>
    class CeilTimeout(async_timeout.timeout):
TypeError: function() argument 1 must be code, not str
```

Any suggestion?

**Comment by WenMellors** [comment]
From the output, it seems that this error is caused by `geopy` or  `aiohttp` (two python packages). So, I think the problem is with the python environment. Here is our recommended python package requirements (see more in [requirements.txt](https://github.com/LibCity/Bigscity-LibCity/blob/master/requirements.txt)):
```
geopy==2.0.0
aiohttp==3.7.4
```
You can test that if you can run `from geopy import distance` correctly.

**Comment by Mardok95** [comment]
> 
`>>> from geopy import distance
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\Andrea\AppData\Local\Programs\Python\Python37\lib\site-packages\geopy\__init__.py", line 12, in <module>
    from geopy.geocoders import *  # noqa
  File "C:\Users\Andrea\AppData\Local\Programs\Python\Python37\lib\site-packages\geopy\geocoders\__init__.py", line 221, in <module>
    from geopy.geocoders.algolia import AlgoliaPlaces
  File "C:\Users\Andrea\AppData\Local\Programs\Python\Python37\lib\site-packages\geopy\geocoders\algolia.py", line 5, in <module>
    from geopy.geocoders.base import DEFAULT_SENTINEL, Geocoder
  File "C:\Users\Andrea\AppData\Local\Programs\Python\Python37\lib\site-packages\geopy\geocoders\base.py", line 7, in <module>
    from geopy.adapters import (
  File "C:\Users\Andrea\AppData\Local\Programs\Python\Python37\lib\site-packages\geopy\adapters.py", line 53, in <module>
    import aiohttp
  File "C:\Users\Andrea\AppData\Local\Programs\Python\Python37\lib\site-packages\aiohttp\__init__.py", line 6, in <module>
    from .client import (
  File "C:\Users\Andrea\AppData\Local\Programs\Python\Python37\lib\site-packages\aiohttp\client.py", line 35, in <module>
    from . import hdrs, http, payload
  File "C:\Users\Andrea\AppData\Local\Programs\Python\Python37\lib\site-packages\aiohttp\http.py", line 7, in <module>
    from .http_parser import (
  File "C:\Users\Andrea\AppData\Local\Programs\Python\Python37\lib\site-packages\aiohttp\http_parser.py", line 15, in <module>
    from .helpers import NO_EXTENSIONS, BaseTimerContext
  File "C:\Users\Andrea\AppData\Local\Programs\Python\Python37\lib\site-packages\aiohttp\helpers.py", line 667, in <module>
    class CeilTimeout(async_timeout.timeout):
TypeError: function() argument 1 must be code, not str`

Yeah the problem is linked with geopy. If i run `pip install -r requirements.txt` i obtain :

`Requirement already satisfied: geopy==2.0.0`
Now i'll try to reinstall that package.

**Comment by Mardok95** [comment]
The problem was caused by aiohttp. I reinstalled geopy and aiohttp and worked. Thank you!
